name: docker-build

on:
  push:
    branches:
      - master

jobs:
  build:
    name: build
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and push Docker images
        uses: docker/build-push-action@v1.1.0
        with:
          registry: docker.pkg.github.com
          username: sangnt2903
          password: ${{ secrets.GHCR_PAT }}
          dockerfile: ./Dockerfile
          repository: sangnt2903/game-tournament/game-tournament
          tags: latest
